<a href="https://colab.research.google.com/github/bugsotim/INTERNSHIP_CN_2026/blob/main/Dashboard_CN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install streamlit pandas openpyxl -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 50.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 62.7 MB/s eta 0:00:00

In [3]:
import streamlit as st
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# โหลดไฟล์ข้อมูล

In [6]:
df = pd.read_csv('/content/drive/MyDrive/ฝึกงาน CN/Sales_report_consignment 20.04.2026 to Dashboard.csv')
display(df.head())

/tmp/ipykernel_17199/1847893104.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/ฝึกงาน CN/Sales_report_consignment 20.04.2026 to Dashboard.csv')

,วันที่,วัน,ปี-เดือน,Weekly on month,ปี,ชื่อลูกค้า,ประเภทสาขา,สาขา,Zone,Town,...,มูลค่ารวม,ประเภทโปรโมชั่น,ราคาเต็ม,ส่วนลด,%GP,ใบลดหนี้,ยอดขายหลังหักใบลดหนี้,ยอดขายหลังหักGP,ยอดขายหลังหักภาษี,Unnamed: 23
0,1 January 2026,พฤหัสบดี,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-THALANG,ถลาง,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
1,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-KHONKAEN,ขอนแก่น,ขอนแก่น,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
2,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-NAKHON PATHOM,นครปฐม,นครปฐม,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
3,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-PHUKET,ภูเก็ต,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
4,3 January 2026,เสาร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-FASHION ISLAND 2,รามอินทรา,กรุงเทพ,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN

In [7]:
df

,วันที่,วัน,ปี-เดือน,Weekly on month,ปี,ชื่อลูกค้า,ประเภทสาขา,สาขา,Zone,Town,...,มูลค่ารวม,ประเภทโปรโมชั่น,ราคาเต็ม,ส่วนลด,%GP,ใบลดหนี้,ยอดขายหลังหักใบลดหนี้,ยอดขายหลังหักGP,ยอดขายหลังหักภาษี,Unnamed: 23
0,1 January 2026,พฤหัสบดี,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-THALANG,ถลาง,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
1,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-KHONKAEN,ขอนแก่น,ขอนแก่น,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
2,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-NAKHON PATHOM,นครปฐม,นครปฐม,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
3,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-PHUKET,ภูเก็ต,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
4,3 January 2026,เสาร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-FASHION ISLAND 2,รามอินทรา,กรุงเทพ,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51465,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,118.00,NaN,59,0%,37%,0.0,118.0,74.34,69.48,NaN
51466,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,59.00,NaN,59,0%,37%,0.0,59.0,37.17,34.74,NaN
51467,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,177.00,NaN,59,0%,37%,0.0,177.0,111.51,104.21,NaN
51468,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,118.00,NaN,59,0%,37%,0.0,118.0,74.34,69.48,NaN
51469,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,236.00,NaN,59,0%,37%,0.0,236.0,148.68,138.95,NaN

## ลบแถวที่เป็นข้อมูลของปี 2025 ออก

In [9]:
print(f"Number of rows before filtering: {len(df)}")

# Filter out rows where 'ปี-เดือน' column contains '2025'
df2 = df[~df['ปี-เดือน'].astype(str).str.contains('2025', na=False)]

print(f"Number of rows after filtering: {len(df)}")
display(df.head())

Number of rows before filtering: 50888
Number of rows after filtering: 50888

,วันที่,วัน,ปี-เดือน,Weekly on month,ปี,ชื่อลูกค้า,ประเภทสาขา,สาขา,Zone,Town,...,มูลค่ารวม,ประเภทโปรโมชั่น,ราคาเต็ม,ส่วนลด,%GP,ใบลดหนี้,ยอดขายหลังหักใบลดหนี้,ยอดขายหลังหักGP,ยอดขายหลังหักภาษี,Unnamed: 23
0,1 January 2026,พฤหัสบดี,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-THALANG,ถลาง,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
1,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-KHONKAEN,ขอนแก่น,ขอนแก่น,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
2,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-NAKHON PATHOM,นครปฐม,นครปฐม,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
3,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-PHUKET,ภูเก็ต,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
4,3 January 2026,เสาร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-FASHION ISLAND 2,รามอินทรา,กรุงเทพ,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN

In [10]:
df2

,วันที่,วัน,ปี-เดือน,Weekly on month,ปี,ชื่อลูกค้า,ประเภทสาขา,สาขา,Zone,Town,...,มูลค่ารวม,ประเภทโปรโมชั่น,ราคาเต็ม,ส่วนลด,%GP,ใบลดหนี้,ยอดขายหลังหักใบลดหนี้,ยอดขายหลังหักGP,ยอดขายหลังหักภาษี,Unnamed: 23
0,1 January 2026,พฤหัสบดี,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-THALANG,ถลาง,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
1,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-KHONKAEN,ขอนแก่น,ขอนแก่น,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
2,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-NAKHON PATHOM,นครปฐม,นครปฐม,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
3,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-PHUKET,ภูเก็ต,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
4,3 January 2026,เสาร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-FASHION ISLAND 2,รามอินทรา,กรุงเทพ,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51465,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,118.00,NaN,59,0%,37%,0.0,118.0,74.34,69.48,NaN
51466,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,59.00,NaN,59,0%,37%,0.0,59.0,37.17,34.74,NaN
51467,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,177.00,NaN,59,0%,37%,0.0,177.0,111.51,104.21,NaN
51468,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,118.00,NaN,59,0%,37%,0.0,118.0,74.34,69.48,NaN
51469,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,236.00,NaN,59,0%,37%,0.0,236.0,148.68,138.95,NaN

## ลบแถวที่คอลัมน์ สาขา มีค่าเป็น Warehouse BMA

In [13]:
print(f"Number of rows in df2 before filtering: {len(df2)}")

df3 = df2[df2['สาขา'] != 'Warehouse BMA']

print(f"Number of rows in df2 after filtering: {len(df2)}")
display(df3.head())

Number of rows in df2 before filtering: 50886
Number of rows in df2 after filtering: 50886

,วันที่,วัน,ปี-เดือน,Weekly on month,ปี,ชื่อลูกค้า,ประเภทสาขา,สาขา,Zone,Town,...,มูลค่ารวม,ประเภทโปรโมชั่น,ราคาเต็ม,ส่วนลด,%GP,ใบลดหนี้,ยอดขายหลังหักใบลดหนี้,ยอดขายหลังหักGP,ยอดขายหลังหักภาษี,Unnamed: 23
0,1 January 2026,พฤหัสบดี,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-THALANG,ถลาง,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
1,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-KHONKAEN,ขอนแก่น,ขอนแก่น,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
2,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-NAKHON PATHOM,นครปฐม,นครปฐม,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
3,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-PHUKET,ภูเก็ต,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
4,3 January 2026,เสาร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-FASHION ISLAND 2,รามอินทรา,กรุงเทพ,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN

In [14]:
df3

,วันที่,วัน,ปี-เดือน,Weekly on month,ปี,ชื่อลูกค้า,ประเภทสาขา,สาขา,Zone,Town,...,มูลค่ารวม,ประเภทโปรโมชั่น,ราคาเต็ม,ส่วนลด,%GP,ใบลดหนี้,ยอดขายหลังหักใบลดหนี้,ยอดขายหลังหักGP,ยอดขายหลังหักภาษี,Unnamed: 23
0,1 January 2026,พฤหัสบดี,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-THALANG,ถลาง,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
1,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-KHONKAEN,ขอนแก่น,ขอนแก่น,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
2,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-NAKHON PATHOM,นครปฐม,นครปฐม,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
3,2 January 2026,ศุกร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-PHUKET,ภูเก็ต,ภูเก็ต,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
4,3 January 2026,เสาร์,ม.ค.-2026,0,2026,KIS,ไม่แยกประเภท,KIS-FASHION ISLAND 2,รามอินทรา,กรุงเทพ,...,399.00,NaN,399,0%,35%,0.0,399.0,259.35,242.38,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51465,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,118.00,NaN,59,0%,37%,0.0,118.0,74.34,69.48,NaN
51466,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,59.00,NaN,59,0%,37%,0.0,59.0,37.17,34.74,NaN
51467,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,177.00,NaN,59,0%,37%,0.0,177.0,111.51,104.21,NaN
51468,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,118.00,NaN,59,0%,37%,0.0,118.0,74.34,69.48,NaN
51469,19 April 2026,อาทิตย์,เม.ย.-2026,2,2026,บริษัท คอนวี่ อินเตอร์เนชั่นแนล จำกัด *KONVY,ไม่แยกประเภท,รวมทุกสาขา,ALL Area,ALL Area,...,236.00,NaN,59,0%,37%,0.0,236.0,148.68,138.95,NaN

## เติมค่าว่างของคอลัมน์