<a href="https://colab.research.google.com/github/bugsotim/INTERNSHIP_CN_2026/blob/main/shopee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

import os
# List the contents of your Google Drive
# You might need to adjust the path if your data is in a specific subfolder
print(os.listdir('/content/drive/MyDrive'))

Mounted at /content/drive
['บัตรประชาชน(สำเนา).pdf', 'Classroom', 'แบบฝึกหัดบทที่ 1 เวกเตอร์.pdf', 'แบบฝึกหัดบทที่ 1 เวกเตอร์-6.jpg', 'IMG_2568.jpeg', 'IMG_2569.jpeg', 'แบบฝึกหัดบทที่ 2 แรงและการเคลื่อนที่.pdf', 'quiz 2-236.jpg', 'Quiz 3.pdf', 'สำเนาปชช .pdf', 'IMG_2669.jpeg', 'IMG_2927.png', 'แบบฝึกหัดบทที่ 3 งาน พลังงาน และโมเมนตัม.pdf', 'quiz Phy.pdf', 'Homework I.pdf', 'bio hwll.pdf', '663020585-6.pdf', 'GE Untitled ', 'IMG_3605.jpeg', 'Project Eng', 'Eng บ้านอร่อย', '4020 MNN DOC 10-Oct 2566.xls', 'การบ้านภาวะของสิ่งมีชีวิต 663020040-8 และ 663020585-6.pdf', 'LAB1-ศิริวรรณ-นวลวัน-663020585-6 (1).pdf', 'LAB1-ศิริวรรณ-นวลวัน-663020585-6.pdf', 'LAB2-ศิริวรรณ-นวลวัน-663020585-6.pdf', 'Work1- ศิริวรรณ-นวลวัน_663020585-6.pdf', 'Work2-Prob.pdf', 'Meeting Reports', 'GE321415 t2y2566 sec02 (SC-SI) group-all [AI-BlockChain-Cloud-BigData] 2024-01-15 1300-1600.pptx', 'Work3a-RV-X.pdf', 'Work3b-การแจกแจงของ RV .pdf', 'GE321415_t2y2566_sec02_work06_group00 (SC-SI) 2024-01-30 1300-1600.gdoc', 'GE321415_t2y2566_sec02_work06_group00 (SC-SI) 2024-01-30 1300-1600.docx', 'inbound4336675718785241338.jpg', 'Work3c-การแจกแจงของตัวสถิติ.pdf', 'Copy of GE321415_t2y2566_sec02_work05_รหัสนักศึกษา_ชื่อ-สกุล_เลขที่ 00 [2024-02-06 13.00-16.00].gdoc', 'Lab 3.pdf', 'GE321415_t2y2566_sec02_Personal_Project_63020585-6_เลขที่ 35_นางสาวศิริวรรณ_นวลวัน.MP4', 'Work4-5_EstimationAndHypo (1).pdf', 'แจ้งเตือนการส่งเอกสารประกอบการขอกู้ยืม สำห~ายเก่าเลื่อนชั้นปี(ต่อเนื่องมข.) ปีการศึกษา2567.pdf', 'Test.gdoc', '014125195120CTF08879.jpeg', 'งานครั้งที่ 2_กลุ่มที่ 3_ค่าเฟในหอสมุด.pdf', 'HW1.pdf', 'Blank Quiz.gform', 'Untitled form (1).gform', 'พิงค์.JPG', 'Untitled form.gform', 'Untitled form (Responses).gsheet', 'inbound4928954223159794482.png', 'คลิป ใบงานที่ 5.2 ', 'TKpart (2).docx', 'TKpart (1).docx', 'TKpart.docx', 'Colab Notebooks', 'กำหนดการmini sct.docx', 'กำหนดการmini sct.gdoc', 'inbound3997147700145853896.png', 'Lab01_663020585-6(ลา).gdoc', 'BISD201224.gsheet', 'Untitled spreadsheet.gsheet', 'Copy of FINANCIAL_STATEMENTS cp.xlsx', 'Copy of .archFINANCIAL_STATEMENTS.xlsx', 'Lab04_Basic SQL.gdoc', 'CO2 Emissions_Canada.csv.xls', 'Lab04_663020585-6_ศิริวรรณ นวลวัน.gdoc', 'Copy of Database_Lab_Exam_01 (1).pdf', 'Copy of Database_Lab_Exam_01.docx', 'Copy of Database_Lab_Exam_01.pdf', 'IMG_7479 (1).jpeg', 'IMG_7479.jpeg', 'IMG_7480 (1).jpeg', 'IMG_7480.jpeg', 'inbound2459205894481883932.jpg', 'บทอิ้ง3.gdoc', 'IMG_7499.jpeg', 'Use case diagram ของการสั้งซื้อพิซซ่า ชุดไก่และเครื่องดื่ม แบบออนไลน์.drawio', 'Use case diagram ของการสั้งซื้อพิซซ่า ชุดไก่และเครื่องดื่ม แบบออนไลน์.jpg', 'Use case diagram ของการสั้งซื้อพิซซ่า ชุดไก่และเครื่องดื่ม แบบออนไลน์.drawio.png', 'S__8192006.jpg', 'ER database final.drawio', 'database', 'Copy of Goodness-of-fit.xlsx', 'รายชื่อนักศึกษาปี 3 รหัส 66 สถิติและวิทยาการข้อมูล วิชาเอกสถิติศาสตร์.doc.gdoc', 'รายชื่อนักศึกษาปี 3 รหัส 66 สถิติและวิทยาการข~มูล วิชาเอกสารสนเทศสถิติและวิทยาการข้อมูล.doc.gdoc', 'งานเขียนภูกระดึง.gdoc', 'งานเขียนภูกระดึง.docx', 'งายเขียน correlation.gdoc', 'เช็คพัสดุSci Week.gsheet', 'Data_Viz_2025', 'Untitled document (3).gdoc', 'Copy of พัสดุ SCIWEEK สาขาสถิติ 2568.gsheet', 'เบิกพัสดุสโม', 'ชีตปริ้นงาน.gsheet', 'เปรมงาน.gdoc', 'Dataset minipro prem', 'ภาวะผู้นำ กล่ม2.gdoc', 'DW part2', 'สื่อสารวิทย์พาร์ท3.gdoc', 'MY BUSINESS ธุรกิจที่ฉันอยากทำ V2.gdoc', 'Clip GE ภาวะผู้นำ', 'บทพูดโปรเจคเปรม.gdoc', 'แปลสลได์.gdoc', 'เมื่อธรรมชาติคือผู้กำกับซอมบี้.pdf', 'Data Warehouse Health NCDs.gsheet', 'Untitled document (2).gdoc', 'งาน อ.ญา.gdoc', 'MY BUSINESS ธุรกิจที่ฉันอยากทำ V2.docx', 'เล่ม GE ผู้ประกอบการ.docx', 'IMG_8398.jpeg', 'คลิปโต้วาทีกลุ่ม 2 ', 'สคริป GE วันศุกร์.gdoc', 'แบบประเมินภาพรวม.gdoc', 'Untitled document (1).gdoc', 'กลยุทธ์.gdoc', 'เหล้ารอบที่n.gsheet', '1764392533734.jpg', 'Copy of Unit 1: Activity 1 - Vocab Review.gdoc', 'BSC', 'Copy of การจัดการรายการบรรณานุกรมด้วยโปรแกรม zotero และ เครื่องมือ AI for research : SciSpace  8-9 ธ.ค. 68.gslides', 'บัตรปชชของศิริวรรณ.pdf', 'Copy of สำเนาของ Unit 2: Face to Face with the Past.gdoc', 'แบบฟอร์มงาน C1.docx', 'CRM การเขียนอ้างอิง.gdoc', 'IMG_20251224_095335_529.webp', 'ขอเป็นไฟล์ด้วย.gsheet', 'ข้อ3 ทำผิดรึป่าว.gsheet', 'ทำใหม่ข้อนี้.gsheet', 'IMG_20260107_094554_251.webp', 'sec02_กลุ่มนี้ดีมาก_D2.gdoc', 'IMG_20260108_130926_152 (2).webp', 'IMG_20260108_130926_152 (1).webp', 'IMG_20260108_130926_152.webp', 'Sec02_Ahoi_D3.pdf', 'Copy of Present perfect .docx', 'Copy of Unit 3 Writing Worksheet-New.docx', 'BSC DPDM midterm 2025', 'Untitled document.gdoc', 'HII_daily_rainfall_2025-07-01.gsheet', 'Y_monthly_rain_HII_operation.gsheet', 'Copy of Copy of Parallel Structure.docx', 'Copy of Unit 5 vocab exercise.docx', 'IMG_9630.png', 'inbound6899709073987379101.jpg', 'IMG_9750.jpeg', 'Sec02_Ahoi_D5-1.docx', 'EDM', 'Resume', 'KKU_Workshop3', 'Meet Recordings', 'test 2', 'สหกิจ', 'คลิปสหกิจ', 'KKU3', 'BSC_DPDM', 'พรีโปรเจคต้น.gdoc', 'กลุ่ม 4 AI.gdoc', 'Sec02_Ahoi_D7.gdoc', 'Research ลงพื้นที่', 'Linear Programing', 'ฝึกงาน CN', 'Internship2026', 'intern CHN', 'DN.gdoc', 'สัมมนา.gdoc', 'สัมมนา.pdf']

In [4]:
import pandas as pd

# 2024
file_path = '/content/drive/MyDrive/intern CHN/shopee2024/2024-01-01_2024-01-31.xlsx'
file_path1 = '/content/drive/MyDrive/intern CHN/shopee2024/2024-02-01_2024-02-29.xlsx'
file_path2 = '/content/drive/MyDrive/intern CHN/shopee2024/2024-03-01_2024-03-31.xlsx'
# 2025
file_path3 = '/content/drive/MyDrive/intern CHN/shopee2025/2025-01-01_2025-01-31_part_1_of_3.xlsx'
file_path4 = '/content/drive/MyDrive/intern CHN/shopee2025/2025-01-01_2025-01-31_part_2_of_3.xlsx'
file_path5 = '/content/drive/MyDrive/intern CHN/shopee2025/2025-01-01_2025-01-31_part_3_of_3.xlsx'
file_path6 ='/content/drive/MyDrive/intern CHN/shopee2025/2025-02-01_2025-02-28_part_1_of_4.xlsx'
file_path7 = '/content/drive/MyDrive/intern CHN/shopee2025/2025-02-01_2025-02-28_part_2_of_4.xlsx'
file_path8 = '/content/drive/MyDrive/intern CHN/shopee2025/2025-02-01_2025-02-28_part_3_of_4.xlsx'
file_path9 = '/content/drive/MyDrive/intern CHN/shopee2025/2025-02-01_2025-02-28_part_4_of_4.xlsx'
file_path10 = '/content/drive/MyDrive/intern CHN/shopee2025/2025-03-01_2025-03-31_part_1_of_4.xlsx'
file_path11 = '/content/drive/MyDrive/intern CHN/shopee2025/2025-03-01_2025-03-31_part_2_of_4.xlsx'
file_path12 = '/content/drive/MyDrive/intern CHN/shopee2025/2025-03-01_2025-03-31_part_3_of_4.xlsx'
file_path13 = '/content/drive/MyDrive/intern CHN/shopee2025/2025-03-01_2025-03-31_part_4_of_4.xlsx'
# 2026
file_path14 = '/content/drive/MyDrive/intern CHN/shopee2026/2026-01-01_2026-01-31_part_1_of_3.xlsx'
file_path15 = '/content/drive/MyDrive/intern CHN/shopee2026/2026-01-01_2026-01-31_part_2_of_3.xlsx'
file_path16 = '/content/drive/MyDrive/intern CHN/shopee2026/2026-01-01_2026-01-31_part_3_of_3.xlsx'
file_path17 = '/content/drive/MyDrive/intern CHN/shopee2026/2026-02-01_2026-02-28_part_1_of_3.xlsx'
file_path18 = '/content/drive/MyDrive/intern CHN/shopee2026/2026-02-01_2026-02-28_part_2_of_3.xlsx'
file_path19 = '/content/drive/MyDrive/intern CHN/shopee2026/2026-02-01_2026-02-28_part_3_of_3.xlsx'
file_path20 = '/content/drive/MyDrive/intern CHN/shopee2026/2026-03-01_2026-03-31_part_1_of_3.xlsx'
file_path21 = '/content/drive/MyDrive/intern CHN/shopee2026/2026-03-01_2026-03-31_part_2_of_3.xlsx'
file_path22 = '/content/drive/MyDrive/intern CHN/shopee2026/2026-03-01_2026-03-31_part_3_of_3.xlsx'

In [5]:
df_2024_1 = pd.read_excel(file_path)
df_2024_2 = pd.read_excel(file_path1)
df_2024_3 = pd.read_excel(file_path2)
df_2025_1_13 = pd.read_excel(file_path3)
df_2025_1_23 =  pd.read_excel(file_path4)
df_2025_1_33 =  pd.read_excel(file_path5)
df_2025_2_14 =  pd.read_excel(file_path6)
df_2025_2_24 =  pd.read_excel(file_path7)
df_2025_2_34 =  pd.read_excel(file_path8)
df_2025_2_44 =  pd.read_excel(file_path9)
df_2025_3_14 =  pd.read_excel(file_path10)
df_2025_3_24 =  pd.read_excel(file_path11)
df_2025_3_34 =  pd.read_excel(file_path12)
df_2025_3_44 =  pd.read_excel(file_path13)
df_2026_1_13 =  pd.read_excel(file_path14)
df_2026_1_23 =  pd.read_excel(file_path15)
df_2026_1_33 =  pd.read_excel(file_path16)
df_2026_2_13 =  pd.read_excel(file_path17)
df_2026_2_23 =  pd.read_excel(file_path18)
df_2026_2_33 =  pd.read_excel(file_path19)
df_2026_3_13 =  pd.read_excel(file_path20)
df_2026_3_23 =  pd.read_excel(file_path21)
df_2026_3_33 =  pd.read_excel(file_path22)

In [6]:
import pandas as pd

# เตรียมรายการสำหรับเก็บ DataFrame ที่ขึ้นต้นด้วย 'df_2024'
dfs_2024_prefix = []

# Dynamically collect DataFrames from the global scope that start with 'df_2024'
# Iterate over a copy of globals().items() to avoid RuntimeError if globals() changes during iteration
for var_name, var_value in list(globals().items()):
    if var_name.startswith('df_2024') and isinstance(var_value, pd.DataFrame):
        dfs_2024_prefix.append(var_value)

# รวม DataFrames ที่ขึ้นต้นด้วย 'df_2024'
if dfs_2024_prefix:
    df_2024 = pd.concat(dfs_2024_prefix, ignore_index=True)
    print(f"df_2024 สร้างแล้วด้วย {df_2024.shape[0]} แถว และ {df_2024.shape[1]} คอลัมน์")
else:
    print("ไม่พบข้อมูลสำหรับ DataFrame ที่ขึ้นต้นด้วย 'df_2024'")

df_2024 สร้างแล้วด้วย 4592 แถว และ 73 คอลัมน์

In [7]:
df_2024

,หมายเลขคำสั่งซื้อ,สถานะการสั่งซื้อ,Hot Listing,สถานะการคืนเงินหรือคืนสินค้า,ชื่อผู้ใช้ (ผู้ซื้อ),วันที่ทำการสั่งซื้อ,เวลาการชำระสินค้า,ช่องทางการชำระเงิน,ช่องทางการชำระเงิน (รายละเอียด),แผนการผ่อนชำระ,...,รหัสประจำสาขา,ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป,รายละเอียดที่อยู่,แขวง/ตำบล,เขต/อำเภอ.1,จังหวัด.1,รหัสไปรษณีย์.1,หมายเลขประจำตัวผู้เสียภาษี,หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี,อีเมลสำหรับรับใบกำกับภาษี
0,240103UWX9N588,สำเร็จแล้ว,N,NaN,bam_beebee,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,240103UWX9N588,สำเร็จแล้ว,N,NaN,bam_beebee,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,240103THAPRG1G,สำเร็จแล้ว,N,NaN,preorder_usa,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,240103THAPRG1G,สำเร็จแล้ว,N,NaN,preorder_usa,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,240102SRPHXTVH,สำเร็จแล้ว,N,NaN,mon_090mm,2024-01-02 16:05,2024-01-02 16:35,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4587,240330EUFCVY3C,สำเร็จแล้ว,N,NaN,chanokwanant,2024-03-30 22:09,2024-03-30 22:39,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4588,240331GQM43KQM,สำเร็จแล้ว,N,NaN,sutida1994,2024-03-31 16:05,2024-03-31 16:05,ShopeePay - ตัดบัญชีธนาคาร,NaN,Airpay GIRO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4589,240331GRQE6CEU,สำเร็จแล้ว,N,NaN,asunskipper,2024-03-31 16:25,2024-03-31 17:04,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4590,240330EQK0908C,สำเร็จแล้ว,N,NaN,5ma24kno19,2024-03-30 20:59,2024-03-30 21:29,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4591,240331G6M6HSFB,สำเร็จแล้ว,N,NaN,hbqy5v2g14,2024-03-31 11:01,2024-03-31 11:31,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
import pandas as pd

# เตรียมรายการสำหรับเก็บ DataFrame ที่ขึ้นต้นด้วย 'df_2024'
dfs_2025_prefix = []

# Dynamically collect DataFrames from the global scope that start with 'df_2024'
# Iterate over a copy of globals().items() to avoid RuntimeError if globals() changes during iteration
for var_name, var_value in list(globals().items()):
    if var_name.startswith('df_2025') and isinstance(var_value, pd.DataFrame):
        dfs_2025_prefix.append(var_value)

# รวม DataFrames ที่ขึ้นต้นด้วย 'df_2024'
if dfs_2025_prefix:
    df_2025 = pd.concat(dfs_2025_prefix, ignore_index=True)
    print(f"df_2024 สร้างแล้วด้วย {df_2025.shape[0]} แถว และ {df_2025.shape[1]} คอลัมน์")
else:
    print("ไม่พบข้อมูลสำหรับ DataFrame ที่ขึ้นต้นด้วย 'df_2025'")

df_2024 สร้างแล้วด้วย 61391 แถว และ 73 คอลัมน์

In [9]:
df_2025

,หมายเลขคำสั่งซื้อ,สถานะการสั่งซื้อ,Hot Listing,สถานะการคืนเงินหรือคืนสินค้า,ชื่อผู้ใช้ (ผู้ซื้อ),วันที่ทำการสั่งซื้อ,เวลาการชำระสินค้า,ช่องทางการชำระเงิน,ช่องทางการชำระเงิน (รายละเอียด),แผนการผ่อนชำระ,...,รหัสประจำสาขา,ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป,รายละเอียดที่อยู่,แขวง/ตำบล,เขต/อำเภอ.1,จังหวัด.1,รหัสไปรษณีย์.1,หมายเลขประจำตัวผู้เสียภาษี,หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี,อีเมลสำหรับรับใบกำกับภาษี
0,250102E0B7D4X4,สำเร็จแล้ว,N,NaN,wy2t1sqihe,2025-01-02 08:43,2025-01-02 09:13,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,250102EFV9RQUW,สำเร็จแล้ว,N,NaN,piyathida0604,2025-01-02 13:21,2025-01-02 13:51,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,250102E8FJSDXV,สำเร็จแล้ว,N,NaN,wanichaya180147,2025-01-02 11:09,2025-01-02 11:39,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,250102ECJPV9NA,สำเร็จแล้ว,N,NaN,ket_bas,2025-01-02 12:22,2025-01-02 12:52,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,250102ECJPV9NA,สำเร็จแล้ว,N,NaN,ket_bas,2025-01-02 12:22,2025-01-02 12:52,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61386,2503313BJWES1M,สำเร็จแล้ว,N,NaN,u56xpejxiv,2025-03-31 17:18,2025-03-31 17:48,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61387,2503313DPTU102,สำเร็จแล้ว,N,NaN,kankamonpipatpong,2025-03-31 17:56,2025-03-31 17:57,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61388,2503313NWV1AH4,สำเร็จแล้ว,N,NaN,siriporn70912,2025-03-31 20:23,2025-03-31 20:24,SPayLater,Special SPayLater,Shopee Credit x5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61389,2503313T8N9VRG,สำเร็จแล้ว,N,NaN,y5r5m8ln0u,2025-03-31 21:41,2025-03-31 22:11,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61390,2503313T8N9VRG,สำเร็จแล้ว,N,NaN,y5r5m8ln0u,2025-03-31 21:41,2025-03-31 22:11,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
import pandas as pd

# เตรียมรายการสำหรับเก็บ DataFrame ที่ขึ้นต้นด้วย 'df_2024'
dfs_2026_prefix = []

# Dynamically collect DataFrames from the global scope that start with 'df_2024'
# Iterate over a copy of globals().items() to avoid RuntimeError if globals() changes during iteration
for var_name, var_value in list(globals().items()):
    if var_name.startswith('df_2026') and isinstance(var_value, pd.DataFrame):
        dfs_2026_prefix.append(var_value)

# รวม DataFrames ที่ขึ้นต้นด้วย 'df_2024'
if dfs_2026_prefix:
    df_2026 = pd.concat(dfs_2026_prefix, ignore_index=True)
    print(f"df_2026 สร้างแล้วด้วย {df_2026.shape[0]} แถว และ {df_2026.shape[1]} คอลัมน์")
else:
    print("ไม่พบข้อมูลสำหรับ DataFrame ที่ขึ้นต้นด้วย 'df_2026'")

df_2026 สร้างแล้วด้วย 52091 แถว และ 73 คอลัมน์

In [11]:
df_2026

,หมายเลขคำสั่งซื้อ,สถานะการสั่งซื้อ,Hot Listing,สถานะการคืนเงินหรือคืนสินค้า,ชื่อผู้ใช้ (ผู้ซื้อ),วันที่ทำการสั่งซื้อ,เวลาการชำระสินค้า,ช่องทางการชำระเงิน,ช่องทางการชำระเงิน (รายละเอียด),แผนการผ่อนชำระ,...,รหัสประจำสาขา,ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป,รายละเอียดที่อยู่,แขวง/ตำบล,เขต/อำเภอ.1,จังหวัด.1,รหัสไปรษณีย์.1,หมายเลขประจำตัวผู้เสียภาษี,หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี,อีเมลสำหรับรับใบกำกับภาษี
0,2601020MK5JEW9,สำเร็จแล้ว,N,NaN,suwannasrithon,2026-01-02 10:01,2026-01-02 10:02,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2601020T07MDUW,สำเร็จแล้ว,N,NaN,chalichi29,2026-01-02 11:38,2026-01-02 11:38,SPayLater,Special SPayLater,Shopee Credit x12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,260101U6S1XGNM,สำเร็จแล้ว,N,NaN,ihd5qo0pn9,2026-01-01 09:49,2026-01-01 09:50,ShopeePay - ตัดบัญชีธนาคาร,NaN,KBank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2601020R8DBG19,สำเร็จแล้ว,N,NaN,namfonkamonwan55,2026-01-02 11:07,2026-01-02 11:07,SPayLater,Special SPayLater,Shopee Credit x5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,260102VSK57ES2,สำเร็จแล้ว,N,NaN,wemincing,2026-01-02 00:59,2026-01-02 00:59,Mobile Banking,NaN,iBanking Payment V2 (K Plus),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52086,260331JHGT5Q6J,สำเร็จแล้ว,N,NaN,isbaleskin.25,2026-03-31 13:21,2026-03-31 13:21,SPayLater,Special SPayLater,Shopee Credit BNPL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52087,260401KMUCRTYX,สำเร็จแล้ว,N,NaN,kaewpongsorn,2026-03-31 23:53,2026-03-31 23:54,ShopeePay - ตัดบัญชีธนาคาร,NaN,KBank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52088,260401KMUCRTYX,สำเร็จแล้ว,N,NaN,kaewpongsorn,2026-03-31 23:53,2026-03-31 23:54,ShopeePay - ตัดบัญชีธนาคาร,NaN,KBank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52089,260331JQFA1UTK,สำเร็จแล้ว,N,NaN,thiraphornwongchan,2026-03-31 15:08,2026-03-31 15:08,SPayLater,Special SPayLater,Shopee Credit x5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52090,260331KGWSY0SN,สำเร็จแล้ว,N,NaN,mysosaddd,2026-03-31 22:43,2026-03-31 23:13,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
import pandas as pd

# รวม DataFrames df_2024, df_2025, และ df_2026 เข้าด้วยกัน
# ตรวจสอบว่า DataFrames มีอยู่ก่อนที่จะทำการรวม

all_dfs_to_concat = []

if 'df_2024' in locals() and not df_2024.empty:
    all_dfs_to_concat.append(df_2024)
    print(f"df_2024 มี {df_2024.shape[0]} แถว")
else:
    print("ไม่พบ df_2024 หรือเป็น DataFrame ว่าง")

if 'df_2025' in locals() and not df_2025.empty:
    all_dfs_to_concat.append(df_2025)
    print(f"df_2025 มี {df_2025.shape[0]} แถว")
else:
    print("ไม่พบ df_2025 หรือเป็น DataFrame ว่าง")

if 'df_2026' in locals() and not df_2026.empty:
    all_dfs_to_concat.append(df_2026)
    print(f"df_2026 มี {df_2026.shape[0]} แถว")
else:
    print("ไม่พบ df_2026 หรือเป็น DataFrame ว่าง")

if all_dfs_to_concat:
    shopee = pd.concat(all_dfs_to_concat, ignore_index=True)
    print(f"\nDataFrame 'shopee' สร้างแล้วด้วย {shopee.shape[0]} แถว และ {shopee.shape[1]} คอลัมน์")
else:
    print("ไม่พบ DataFrame ที่จะนำมารวมกัน ไม่มี DataFrame 'shopee' ถูกสร้างขึ้น")

df_2024 มี 4592 แถว
df_2025 มี 61391 แถว
df_2026 มี 52091 แถว

DataFrame 'shopee' สร้างแล้วด้วย 118074 แถว และ 73 คอลัมน์

In [13]:
shopee

,หมายเลขคำสั่งซื้อ,สถานะการสั่งซื้อ,Hot Listing,สถานะการคืนเงินหรือคืนสินค้า,ชื่อผู้ใช้ (ผู้ซื้อ),วันที่ทำการสั่งซื้อ,เวลาการชำระสินค้า,ช่องทางการชำระเงิน,ช่องทางการชำระเงิน (รายละเอียด),แผนการผ่อนชำระ,...,รหัสประจำสาขา,ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป,รายละเอียดที่อยู่,แขวง/ตำบล,เขต/อำเภอ.1,จังหวัด.1,รหัสไปรษณีย์.1,หมายเลขประจำตัวผู้เสียภาษี,หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี,อีเมลสำหรับรับใบกำกับภาษี
0,240103UWX9N588,สำเร็จแล้ว,N,NaN,bam_beebee,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,240103UWX9N588,สำเร็จแล้ว,N,NaN,bam_beebee,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,240103THAPRG1G,สำเร็จแล้ว,N,NaN,preorder_usa,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,240103THAPRG1G,สำเร็จแล้ว,N,NaN,preorder_usa,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,240102SRPHXTVH,สำเร็จแล้ว,N,NaN,mon_090mm,2024-01-02 16:05,2024-01-02 16:35,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118069,260331JHGT5Q6J,สำเร็จแล้ว,N,NaN,isbaleskin.25,2026-03-31 13:21,2026-03-31 13:21,SPayLater,Special SPayLater,Shopee Credit BNPL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118070,260401KMUCRTYX,สำเร็จแล้ว,N,NaN,kaewpongsorn,2026-03-31 23:53,2026-03-31 23:54,ShopeePay - ตัดบัญชีธนาคาร,NaN,KBank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118071,260401KMUCRTYX,สำเร็จแล้ว,N,NaN,kaewpongsorn,2026-03-31 23:53,2026-03-31 23:54,ShopeePay - ตัดบัญชีธนาคาร,NaN,KBank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118072,260331JQFA1UTK,สำเร็จแล้ว,N,NaN,thiraphornwongchan,2026-03-31 15:08,2026-03-31 15:08,SPayLater,Special SPayLater,Shopee Credit x5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118073,260331KGWSY0SN,สำเร็จแล้ว,N,NaN,mysosaddd,2026-03-31 22:43,2026-03-31 23:13,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
output_path = '/content/drive/MyDrive/intern CHN/shopee_combined_data.xlsx'
shopee.to_excel(output_path, index=False)
print(f"DataFrame 'shopee' ถูกส่งออกไปยัง '{output_path}' เรียบร้อยแล้ว")

Exception ignored in: <function ZipFile.__del__ at 0x7df4332f7ec0>
Traceback (most recent call last):
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1964, in __del__
    def __del__(self):

KeyboardInterrupt:

DataFrame 'shopee' ถูกส่งออกไปยัง '/content/drive/MyDrive/intern CHN/shopee_combined_data.xlsx' เรียบร้อยแล้ว

In [20]:
file_path_01 = '/content/drive/MyDrive/intern CHN/shopee_combined_data.xlsx'

In [22]:
shopee1=  pd.read_excel(file_path_01)

In [23]:
shopee1.shape

(118074, 73)

In [24]:
shopee1

,หมายเลขคำสั่งซื้อ,สถานะการสั่งซื้อ,Hot Listing,สถานะการคืนเงินหรือคืนสินค้า,ชื่อผู้ใช้ (ผู้ซื้อ),วันที่ทำการสั่งซื้อ,เวลาการชำระสินค้า,ช่องทางการชำระเงิน,ช่องทางการชำระเงิน (รายละเอียด),แผนการผ่อนชำระ,...,รหัสประจำสาขา,ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป,รายละเอียดที่อยู่,แขวง/ตำบล,เขต/อำเภอ.1,จังหวัด.1,รหัสไปรษณีย์.1,หมายเลขประจำตัวผู้เสียภาษี,หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี,อีเมลสำหรับรับใบกำกับภาษี
0,240103UWX9N588,สำเร็จแล้ว,N,NaN,bam_beebee,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,240103UWX9N588,สำเร็จแล้ว,N,NaN,bam_beebee,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,240103THAPRG1G,สำเร็จแล้ว,N,NaN,preorder_usa,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,240103THAPRG1G,สำเร็จแล้ว,N,NaN,preorder_usa,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,240102SRPHXTVH,สำเร็จแล้ว,N,NaN,mon_090mm,2024-01-02 16:05,2024-01-02 16:35,เก็บเงินปลายทาง,NaN,Cash on Delivery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118069,260331JHGT5Q6J,สำเร็จแล้ว,N,NaN,isbaleskin.25,2026-03-31 13:21,2026-03-31 13:21,SPayLater,Special SPayLater,Shopee Credit BNPL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118070,260401KMUCRTYX,สำเร็จแล้ว,N,NaN,kaewpongsorn,2026-03-31 23:53,2026-03-31 23:54,ShopeePay - ตัดบัญชีธนาคาร,NaN,KBank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118071,260401KMUCRTYX,สำเร็จแล้ว,N,NaN,kaewpongsorn,2026-03-31 23:53,2026-03-31 23:54,ShopeePay - ตัดบัญชีธนาคาร,NaN,KBank,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118072,260331JQFA1UTK,สำเร็จแล้ว,N,NaN,thiraphornwongchan,2026-03-31 15:08,2026-03-31 15:08,SPayLater,Special SPayLater,Shopee Credit x5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118073,260331KGWSY0SN,สำเร็จแล้ว,N,NaN,mysosaddd,2026-03-31 22:43,2026-03-31 23:13,QR พร้อมเพย์,NaN,PromptPay QR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
columns_to_drop = [
    'สถานะการสั่งซื้อ',
    'Hot Listing',
    'ชื่อผู้ใช้ (ผู้ซื้อ)',
    'วิธีการจัดส่ง',
    'หมายเลขติดตามพัสดุ',
    'เลขอ้างอิง Parent SKU',
    'โค้ด Coins Cashback ชำระโดยผู้ขาย',
    'โค้ดส่วนลด',
    'เข้าร่วมแคมเปญ bundle deal หรือไม่',
    'ส่วนลด bundle deal ชำระโดยผู้ขาย',
    'ส่วนลด bundle deal ชำระโดย Shopee',
    'โปรโมชั่นช่องทางชำระเงินทั้งหมด',
    'ส่วนลดเครื่องเก่าแลกใหม่',
    'โบนัสส่วนลดเครื่องเก่าแลกใหม่',
    'Transaction Fee',
    'ค่าจัดส่งที่ชำระโดยผู้ซื้อ',
    'ค่าจัดส่งที่ Shopee ออกให้โดยประมาณ',
    'ค่าจัดส่งสินค้าคืน',
    'โบนัสส่วนลดเครื่องเก่าแลกใหม่จากผู้ขาย',
    'ชื่อผู้รับ',
    'หมายเลขโทรศัพท์',
    'หมายเหตุจากผู้ซื้อ',
    'ที่อยู่ในการจัดส่ง',
    'รหัสไปรษณีย์',
    'ประเภทคำสั่งซื้อ',
    'บันทึก',
    'ผู้ซื้อร้องขอใบกำกับภาษี',
    'ประเภทใบกำกับภาษี',
    'ชื่อ',
    'ประเภทสาขา',
    'ชื่อสาขา',
    'รหัสประจำสาขา',
    'ที่อยู่สำหรับออกใบกำกับภาษีแบบเต็มรูป',
    'รายละเอียดที่อยู่',
    'แขวง/ตำบล',
    'เขต/อำเภอ.1',
    'จังหวัด.1',
    'รหัสไปรษณีย์.1',
    'หมายเลขประจำตัวผู้เสียภาษี',
    'หมายเลขโทรศัพท์สำหรับออกใบกำกับภาษี',
    'อีเมลสำหรับรับใบกำกับภาษี'
]

# Drop the specified columns
shopee1 = shopee1.drop(columns=columns_to_drop, errors='ignore')

print(f"DataFrame 'shopee1' หลังจากลบคอลัมน์: {shopee1.shape[0]} แถว และ {shopee1.shape[1]} คอลัมน์")

DataFrame 'shopee1' หลังจากลบคอลัมน์: 118074 แถว และ 33 คอลัมน์

In [26]:
shopee1

,หมายเลขคำสั่งซื้อ,สถานะการคืนเงินหรือคืนสินค้า,วันที่ทำการสั่งซื้อ,เวลาการชำระสินค้า,ช่องทางการชำระเงิน,ช่องทางการชำระเงิน (รายละเอียด),แผนการผ่อนชำระ,ค่าธรรมเนียม (%),ตัวเลือกการจัดส่ง,*หมายเลขติดตามพัสดุ,...,ส่วนลดจากการใช้เหรียญ,ค่าคอมมิชชั่น,ราคาสินค้าที่ชำระโดยผู้ซื้อ (THB),ค่าบริการ,จำนวนเงินทั้งหมด,ค่าจัดส่งโดยประมาณ,ประเทศ,จังหวัด,เขต/อำเภอ,เวลาที่ทำการสั่งซื้อสำเร็จ
0,240103UWX9N588,NaN,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),3.21%,Standard Delivery - ส่งธรรมดาในประเทศ-J&T Express,624451474253,...,0,52,689,22,734,45,TH,จังหวัดสมุทรปราการ,อำเภอบางพลี,2024-01-04 18:17
1,240103UWX9N588,NaN,2024-01-03 12:44,2024-01-03 12:44,Mobile Banking,NaN,iBanking Payment V2 (SCB),3.21%,Standard Delivery - ส่งธรรมดาในประเทศ-J&T Express,624451474253,...,0,52,689,22,734,45,TH,จังหวัดสมุทรปราการ,อำเภอบางพลี,2024-01-04 18:17
2,240103THAPRG1G,NaN,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,3.21%,Standard Delivery - ส่งธรรมดาในประเทศ-J&T Express,628281250111,...,0,26,315,11,360,45,TH,จังหวัดกรุงเทพมหานคร,เขตจตุจักร,2024-01-04 22:32
3,240103THAPRG1G,NaN,2024-01-02 23:26,2024-01-02 23:26,บัตรเครดิต/บัตรเดบิต,NaN,Airpay Credit Card,3.21%,Standard Delivery - ส่งธรรมดาในประเทศ-J&T Express,628281250111,...,0,26,315,11,360,45,TH,จังหวัดกรุงเทพมหานคร,เขตจตุจักร,2024-01-04 22:32
4,240102SRPHXTVH,NaN,2024-01-02 16:05,2024-01-02 16:35,เก็บเงินปลายทาง,NaN,Cash on Delivery,3.21%,Standard Delivery - ส่งธรรมดาในประเทศ-J&T Express,624257659830,...,0,28,280,12,325,45,TH,จังหวัดขอนแก่น,อำเภอชุมแพ,2024-01-05 00:22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118069,260331JHGT5Q6J,NaN,2026-03-31 13:21,2026-03-31 13:21,SPayLater,Special SPayLater,Shopee Credit BNPL,3.21%,Standard Delivery - ส่งธรรมดาในประเทศ-Flash Ex...,TH01018J3YUQ4B1,...,0,17,118,19,118,35,TH,จังหวัดกรุงเทพมหานคร,เขตคลองเตย,2026-04-19 20:33
118070,260401KMUCRTYX,NaN,2026-03-31 23:53,2026-03-31 23:54,ShopeePay - ตัดบัญชีธนาคาร,NaN,KBank,3.21%,Standard Delivery - ส่งธรรมดาในประเทศ-Flash Ex...,TH02048J3YUQ2N,...,0,13,97,14,97,35,TH,จังหวัดสมุทรปราการ,อำเภอพระประแดง,2026-04-20 12:38
118071,260401KMUCRTYX,NaN,2026-03-31 23:53,2026-03-31 23:54,ShopeePay - ตัดบัญชีธนาคาร,NaN,KBank,3.21%,Standard Delivery - ส่งธรรมดาในประเทศ-Flash Ex...,TH02048J3YUQ2N,...,0,13,97,14,97,35,TH,จังหวัดสมุทรปราการ,อำเภอพระประแดง,2026-04-20 12:38
118072,260331JQFA1UTK,NaN,2026-03-31 15:08,2026-03-31 15:08,SPayLater,Special SPayLater,Shopee Credit x5,5.89%,Standard Delivery - ส่งธรรมดาในประเทศ-Flash Ex...,TH01378J3YUN2C,...,0,39,332,32,332,35,TH,จังหวัดกรุงเทพมหานคร,เขตราชเทวี,2026-04-20 13:35
118073,260331KGWSY0SN,NaN,2026-03-31 22:43,2026-03-31 23:13,QR พร้อมเพย์,NaN,PromptPay QR,3.21%,Standard Delivery - ส่งธรรมดาในประเทศ-SPX Express,TH267896461618I,...,300,17,124,19,124,38,TH,จังหวัดภูเก็ต,อำเภอถลาง,2026-04-21 16:52