<a href="https://colab.research.google.com/github/bugsotim/INTERNSHIP_CN_2026/blob/main/%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B9%81%E0%B8%97%E0%B8%A3%E0%B9%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import pandas as pd

# Import Data

In [71]:
df_01_2026 = pd.read_csv('/content/2026-1.csv')
df_02_2026 = pd.read_csv('/content/2026-2.csv')
df_03_2026 = pd.read_csv('/content/2026-3.csv')
df_2025 = pd.read_csv('/content/2025-1.csv')
df_2024_Q1 = pd.read_csv('/content/2024_Q1.csv')
df_2024_Q234 = pd.read_csv('/content/2024_Q234.csv')

/tmp/ipykernel_2941/1952785756.py:2: DtypeWarning: Columns (0,5,9,10,11,12,13,14,15,16,17,18,19,20,22,23,29,51,55,56,57,58,59,60,61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  df_02_2026 = pd.read_csv('/content/2026-2.csv')
/tmp/ipykernel_2941/1952785756.py:4: DtypeWarning: Columns (0,5,9,10,11,12,13,14,15,16,17,18,19,20,22,23,29,30,31,51,55,56,57,58,59,60,61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025 = pd.read_csv('/content/2025-1.csv')
/tmp/ipykernel_2941/1952785756.py:5: DtypeWarning: Columns (0,5,9,10,11,12,13,14,15,16,17,18,19,20,22,23,29,30,31,51,55,56,57,58,59,60,61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2024_Q1 = pd.read_csv('/content/2024_Q1.csv')

In [72]:
df_01_2026

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,Platform unique order ID.,Current order status.,NaN,The filed to explain the order is in cancellat...,NaN,Platform SKU ID.,Seller sku input by the seller in the product ...,Platform product name.,Platform SKU variation,SKU sold quantity in the order.,...,NaN,NaN,Yes - buyer requested tax invoice for the orde...,Buyer Tax ID for tax invoice,Personal or Company,Name of the tax invoice issued to,Email address for tax invoice,Phone number for tax invoice,Registered address for tax invoice,Address type if the tax receiver type is busin...
1,582386226186389124,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732950466265450486,8859460201685,แป้งพัฟเจ้านาง To go ขนาด 5g. - Chaonang Perfe...,แป้งพัฟ To go 00,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,582386204436367275,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732261908704954358,8859460201531,Airy คุชชั่นเจ้านางแบบซอง(5ก.) บางเบา ปกปิด คุ...,02 GOLDEN HONEY,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,582386204436367275,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732261908705019894,8859460201548,Airy คุชชั่นเจ้านางแบบซอง(5ก.) บางเบา ปกปิด คุ...,03 CLASSIC TAN,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,582386194640438400,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14190,581906505416804118,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133113334,8859460200459,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14191,581906494218994807,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732950466265450486,8859460201685,แป้งพัฟเจ้านาง To go ขนาด 5g. - Chaonang Perfe...,แป้งพัฟ To go 00,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14192,581906445633684495,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729630925935250422,8857200237710,แป้งเจ้านาง 10ก. (แพคเกจใหม่) - Chaonang Perfe...,01 ผิวขาวอมชมพู,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14193,581906311741015057,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732950466265712630,8859460200954,แป้งพัฟเจ้านาง To go ขนาด 5g. - Chaonang Perfe...,แป้งพัฟ To go C21,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14194,581906193280239218,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732950466265450486,8859460201685,แป้งพัฟเจ้านาง To go ขนาด 5g. - Chaonang Perfe...,แป้งพัฟ To go 00,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
df_02_2026

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,Platform unique order ID.,Current order status.,NaN,The filed to explain the order is in cancellat...,NaN,Platform SKU ID.,Seller sku input by the seller in the product ...,Platform product name.,Platform SKU variation,SKU sold quantity in the order.,...,NaN,NaN,Yes - buyer requested tax invoice for the orde...,Buyer Tax ID for tax invoice,Personal or Company,Name of the tax invoice issued to,Email address for tax invoice,Phone number for tax invoice,Registered address for tax invoice,Address type if the tax receiver type is busin...
1,582837348412917082,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1734421965781895158,GWP_Rose1ml_Centella1ml_Hya1ml,[สินค้าแถม ห้ามกดสั่งซื้อ] เซรั่มเจ้านางขนาดทด...,ค่าเริ่มต้น,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,582837348412917082,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732261908704954358,8859460201531,Airy คุชชั่นเจ้านางแบบซอง(5ก.) บางเบา ปกปิด คุ...,02 GOLDEN HONEY,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,582837066058728767,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1733392274824660982,Togo00_GLS01,แป้งพัฟเจ้านาง To go + รองพื้นซองเจ้านาง สูตร ...,"แป้งTo go 00, รองพื้น Glass Skin 01",1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,582837066058728767,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1734379287094921206,GWP_Rose1ml_Centella1ml_Hya1ml_Brush,[สินค้าแถม ห้ามกดสั่งซื้อ] แปรงแต่งหน้าเจ้านาง...,ค่าเริ่มต้น,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20976,582386498463434234,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732950466265516022,8859460201661,แป้งพัฟเจ้านาง To go ขนาด 5g. - Chaonang Perfe...,แป้งพัฟ To go 01,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20977,582386430031529263,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729630925935250422,8857200237710,แป้งเจ้านาง 10ก. (แพคเกจใหม่) - Chaonang Perfe...,01 ผิวขาวอมชมพู,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20978,582386372449109639,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732950466265450486,8859460201685,แป้งพัฟเจ้านาง To go ขนาด 5g. - Chaonang Perfe...,แป้งพัฟ To go 00,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20979,582386338520074230,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732261908704888822,8859460201524,Airy คุชชั่นเจ้านางแบบซอง(5ก.) บางเบา ปกปิด คุ...,01 IVORY PEARL,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20980,582386319779792579,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729630925935315958,8857200237727,แป้งเจ้านาง 10ก. (แพคเกจใหม่) - Chaonang Perfe...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
df_03_2026

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,Platform unique order ID.,Current order status.,NaN,The filed to explain the order is in cancellat...,NaN,Platform SKU ID.,Seller sku input by the seller in the product ...,Platform product name.,Platform SKU variation,SKU sold quantity in the order.,...,NaN,NaN,Yes - buyer requested tax invoice for the orde...,Buyer Tax ID for tax invoice,Personal or Company,Name of the tax invoice issued to,Email address for tax invoice,Phone number for tax invoice,Registered address for tax invoice,Address type if the tax receiver type is busin...
1,580143273864956533,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729630925935447030,8857200237741,แป้งเจ้านาง 10ก. (แพคเกจใหม่) - Chaonang Perfe...,C21 ผิวขาวเหลือง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,580143273956576181,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729630925935447030,8857200237741,แป้งเจ้านาง 10ก. (แพคเกจใหม่) - Chaonang Perfe...,C21 ผิวขาวเหลือง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,580143269970676555,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440130132642806,8859460201586,แป้งฝุ่นเจ้านาง (6.5ก.) - Chaonang Diamond Tra...,แป้งฝุ่นเจ้านาง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,580143269376985104,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729630925935250422,8857200237710,แป้งเจ้านาง 10ก. (แพคเกจใหม่) - Chaonang Perfe...,01 ผิวขาวอมชมพู,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12882,580032842758720463,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1731728255750999030,8859460201227,(สูตรใหม่) รองพื้นเจ้านางผิวกระจก แบบซอง (5ก.)...,02 Honey Beige ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12883,580032835922790407,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1731728255751064566,8859460201234,(สูตรใหม่) รองพื้นเจ้านางผิวกระจก แบบซอง (5ก.)...,C21 Natural Beige ผิวขาวเหลือง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12884,580032807995082882,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397709302,8859460200374,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#02 ฮันนี่ เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12885,580032806975539529,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133178870,8859460200466,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,03 ผิวเข้ม,5,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12886,580032807731234930,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729963820695456758,8859460200909,คุชชั่นเจ้านาง - Chaonang Glowy Cushion SPF30 ...,02 Honey Beige,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
df_2025

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,Platform unique order ID.,Current order status.,NaN,The filed to explain the order is in cancellat...,NaN,Platform SKU ID.,Seller sku input by the seller in the product ...,Platform product name.,Platform SKU variation,SKU sold quantity in the order.,...,NaN,NaN,Yes - buyer requested tax invoice for the orde...,Buyer Tax ID for tax invoice,Personal or Company,Name of the tax invoice issued to,Email address for tax invoice,Phone number for tax invoice,Registered address for tax invoice,Address type if the tax receiver type is busin...
1,5.81906E+17,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1.73295E+18,8.85946E+12,แป้งพัฟเจ้านาง To go ขนาด 5g. - Chaonang Perfe...,แป้งพัฟ To go 01,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5.81906E+17,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1.72996E+18,8.85946E+12,[หมดอายุ 12/2026] คุชชั่นเจ้านาง - Chaonang Gl...,02 Honey Beige,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5.81906E+17,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1.73295E+18,8.85946E+12,แป้งพัฟเจ้านาง To go ขนาด 5g. - Chaonang Perfe...,แป้งพัฟ To go 00,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.81905E+17,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1.72963E+18,8.8572E+12,แป้งเจ้านาง 10ก. (แพคเกจใหม่) - Chaonang Perfe...,01 ผิวขาวอมชมพู,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174012,579825000000000000.0,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440000000000000.0,8.85946E+12,แป้งฝุ่นเจ้านาง (6.5ก.) - Chaonang Diamond Tra...,แป้งฝุ่นเจ้านาง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174013,579825000000000000.0,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729990000000000000.0,8.85946E+12,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174014,579825000000000000.0,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440000000000000.0,8.85946E+12,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174015,579825000000000000.0,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729630000000000000.0,8.8572E+12,แป้งเจ้านาง 10ก. (แพคเกจใหม่) - Chaonang Perfe...,01 ผิวขาวอมชมพู,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174016,579825000000000000.0,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729990000000000000.0,8.85946E+12,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,01 ผิวขาวอมชมพู,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
df_2024_Q1

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,Platform unique order ID.,Current order status.,NaN,The filed to explain the order is in cancellat...,NaN,Platform SKU ID.,Seller sku input by the seller in the product ...,Platform product name.,Platform SKU variation,SKU sold quantity in the order.,...,NaN,NaN,Yes - buyer requested tax invoice for the orde...,Buyer Tax ID for tax invoice,Personal or Company,Name of the tax invoice issued to,Email address for tax invoice,Phone number for tax invoice,Registered address for tax invoice,Address type if the tax receiver type is busin...
1,579802935673522831,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133178870,8859460200466,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,03 ผิวเข้ม,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,579802882152892916,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,579802825830795537,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133113334,8859460200459,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,579802812881406721,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397643766,8859460200350,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76204,578692199793593146,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397709302,8859460200374,รองพื้นซอง ( 5g.) Chaonang Radiance Skin Found...,#02 ฮันนี่ เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76205,578692195560359954,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397709302,8859460200374,รองพื้นซอง ( 5g.) Chaonang Radiance Skin Found...,#02 ฮันนี่ เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76206,578692192672385161,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นซอง ( 5g.) Chaonang Radiance Skin Found...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76207,578692191937072116,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729963820695587830,8859460200930,คุชชั่นเจ้านาง - Chaonang glowy cushion spf30 ...,C21 Natural Beige,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76208,578692170271262738,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729695374228884470,8857200237802,แป้งเจ้านาง (แพคเกจใหม่) - Chaonang Perfect Br...,04 ผิวสีน้ำผึ้ง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
df_2024_Q234

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,Platform unique order ID.,Current order status.,NaN,The filed to explain the order is in cancellat...,NaN,Platform SKU ID.,Seller sku input by the seller in the product ...,Platform product name.,Platform SKU variation,SKU sold quantity in the order.,...,NaN,NaN,Yes - buyer requested tax invoice for the orde...,Buyer Tax ID for tax invoice,Personal or Company,Name of the tax invoice issued to,Email address for tax invoice,Phone number for tax invoice,Registered address for tax invoice,Address type if the tax receiver type is busin...
1,578692147513428655,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729714490681101302,PFB01FDT1501,โปรสวยสุดคุ้ม 499.- แป้งพัฟ 2 ชั้น +รองพื้นหลอ...,"01 ผิวขาวอมชมพู, 01",1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,578692146001841064,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440130132642806,8859460201586,แป้งฝุ่นเจ้านาง ( Chaonang Diamond Translucent...,แป้งฝุ่นเจ้านาง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,578692123263666888,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729630925935315958,8857200237727,แป้งเจ้านาง (แพคเกจใหม่) - Chaonang Perfect Br...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,578692090397100715,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นซอง ( 5g.) Chaonang Radiance Skin Found...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6971,578314965325351826,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437736950,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6972,578314684407253371,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437736950,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6973,578314672990751326,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,NaN,รองพื้นซอง ( 5g.) Chaonang Radiance Skin Found...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6974,578314661173430826,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437868022,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#03 คลาสสิค แทน,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6975,578314492702198502,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437802486,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#02 ฮันนี่ เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
df_01_2026_cleaned = df_01_2026.iloc[1:].copy()
df_02_2026_cleaned = df_02_2026.iloc[1:].copy()
df_03_2026_cleaned = df_03_2026.iloc[1:].copy()

df2026 = pd.concat([df_01_2026_cleaned, df_02_2026_cleaned, df_03_2026_cleaned], ignore_index=True)

In [79]:
df_2024_Q1

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,Platform unique order ID.,Current order status.,NaN,The filed to explain the order is in cancellat...,NaN,Platform SKU ID.,Seller sku input by the seller in the product ...,Platform product name.,Platform SKU variation,SKU sold quantity in the order.,...,NaN,NaN,Yes - buyer requested tax invoice for the orde...,Buyer Tax ID for tax invoice,Personal or Company,Name of the tax invoice issued to,Email address for tax invoice,Phone number for tax invoice,Registered address for tax invoice,Address type if the tax receiver type is busin...
1,579802935673522831,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133178870,8859460200466,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,03 ผิวเข้ม,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,579802882152892916,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,579802825830795537,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133113334,8859460200459,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,579802812881406721,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397643766,8859460200350,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76204,578692199793593146,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397709302,8859460200374,รองพื้นซอง ( 5g.) Chaonang Radiance Skin Found...,#02 ฮันนี่ เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76205,578692195560359954,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397709302,8859460200374,รองพื้นซอง ( 5g.) Chaonang Radiance Skin Found...,#02 ฮันนี่ เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76206,578692192672385161,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นซอง ( 5g.) Chaonang Radiance Skin Found...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76207,578692191937072116,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729963820695587830,8859460200930,คุชชั่นเจ้านาง - Chaonang glowy cushion spf30 ...,C21 Natural Beige,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76208,578692170271262738,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729695374228884470,8857200237802,แป้งเจ้านาง (แพคเกจใหม่) - Chaonang Perfect Br...,04 ผิวสีน้ำผึ้ง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
df_2024_Q234

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,Platform unique order ID.,Current order status.,NaN,The filed to explain the order is in cancellat...,NaN,Platform SKU ID.,Seller sku input by the seller in the product ...,Platform product name.,Platform SKU variation,SKU sold quantity in the order.,...,NaN,NaN,Yes - buyer requested tax invoice for the orde...,Buyer Tax ID for tax invoice,Personal or Company,Name of the tax invoice issued to,Email address for tax invoice,Phone number for tax invoice,Registered address for tax invoice,Address type if the tax receiver type is busin...
1,578692147513428655,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729714490681101302,PFB01FDT1501,โปรสวยสุดคุ้ม 499.- แป้งพัฟ 2 ชั้น +รองพื้นหลอ...,"01 ผิวขาวอมชมพู, 01",1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,578692146001841064,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440130132642806,8859460201586,แป้งฝุ่นเจ้านาง ( Chaonang Diamond Translucent...,แป้งฝุ่นเจ้านาง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,578692123263666888,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729630925935315958,8857200237727,แป้งเจ้านาง (แพคเกจใหม่) - Chaonang Perfect Br...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,578692090397100715,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นซอง ( 5g.) Chaonang Radiance Skin Found...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6971,578314965325351826,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437736950,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6972,578314684407253371,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437736950,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6973,578314672990751326,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,NaN,รองพื้นซอง ( 5g.) Chaonang Radiance Skin Found...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6974,578314661173430826,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437868022,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#03 คลาสสิค แทน,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6975,578314492702198502,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437802486,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#02 ฮันนี่ เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
df_2025

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,Platform unique order ID.,Current order status.,NaN,The filed to explain the order is in cancellat...,NaN,Platform SKU ID.,Seller sku input by the seller in the product ...,Platform product name.,Platform SKU variation,SKU sold quantity in the order.,...,NaN,NaN,Yes - buyer requested tax invoice for the orde...,Buyer Tax ID for tax invoice,Personal or Company,Name of the tax invoice issued to,Email address for tax invoice,Phone number for tax invoice,Registered address for tax invoice,Address type if the tax receiver type is busin...
1,5.81906E+17,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1.73295E+18,8.85946E+12,แป้งพัฟเจ้านาง To go ขนาด 5g. - Chaonang Perfe...,แป้งพัฟ To go 01,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5.81906E+17,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1.72996E+18,8.85946E+12,[หมดอายุ 12/2026] คุชชั่นเจ้านาง - Chaonang Gl...,02 Honey Beige,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5.81906E+17,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1.73295E+18,8.85946E+12,แป้งพัฟเจ้านาง To go ขนาด 5g. - Chaonang Perfe...,แป้งพัฟ To go 00,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.81905E+17,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1.72963E+18,8.8572E+12,แป้งเจ้านาง 10ก. (แพคเกจใหม่) - Chaonang Perfe...,01 ผิวขาวอมชมพู,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174012,579825000000000000.0,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440000000000000.0,8.85946E+12,แป้งฝุ่นเจ้านาง (6.5ก.) - Chaonang Diamond Tra...,แป้งฝุ่นเจ้านาง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174013,579825000000000000.0,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729990000000000000.0,8.85946E+12,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174014,579825000000000000.0,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440000000000000.0,8.85946E+12,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174015,579825000000000000.0,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729630000000000000.0,8.8572E+12,แป้งเจ้านาง 10ก. (แพคเกจใหม่) - Chaonang Perfe...,01 ผิวขาวอมชมพู,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174016,579825000000000000.0,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729990000000000000.0,8.85946E+12,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,01 ผิวขาวอมชมพู,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Now, I'll convert the `Order Creation Time` column to a datetime object and then sort the `df2026` DataFrame.

In [82]:
df2026['Created Time'] = pd.to_datetime(df2026['Created Time'], format='%d/%m/%Y %H:%M:%S')
df2026 = df2026.sort_values(by='Created Time').reset_index(drop=True)

display(df2026.head())

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,580032807731234930,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729963820695456758,8859460200909,คุชชั่นเจ้านาง - Chaonang Glowy Cushion SPF30 ...,02 Honey Beige,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,580032806975539529,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133178870,8859460200466,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,03 ผิวเข้ม,5,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,580032807995082882,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397709302,8859460200374,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#02 ฮันนี่ เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,580032835922790407,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1731728255751064566,8859460201234,(สูตรใหม่) รองพื้นเจ้านางผิวกระจก แบบซอง (5ก.)...,C21 Natural Beige ผิวขาวเหลือง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,580032842758720463,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1731728255750933494,8859460201210,(สูตรใหม่) รองพื้นเจ้านางผิวกระจก แบบซอง (5ก.)...,01 Ivory ผิวขาวอมชมพู,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
df2026

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,580032807731234930,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729963820695456758,8859460200909,คุชชั่นเจ้านาง - Chaonang Glowy Cushion SPF30 ...,02 Honey Beige,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,580032806975539529,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133178870,8859460200466,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,03 ผิวเข้ม,5,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,580032807995082882,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397709302,8859460200374,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#02 ฮันนี่ เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,580032835922790407,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1731728255751064566,8859460201234,(สูตรใหม่) รองพื้นเจ้านางผิวกระจก แบบซอง (5ก.)...,C21 Natural Beige ผิวขาวเหลือง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,580032842758720463,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1731728255750933494,8859460201210,(สูตรใหม่) รองพื้นเจ้านางผิวกระจก แบบซอง (5ก.)...,01 Ivory ผิวขาวอมชมพู,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48055,582837066058728767,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1734440271410464758,8859460201876,Care skin รองพื้นเจ้านางแคร์สกิน (5ก.) - Chaon...,00 ผิวขาว,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48056,582837066058728767,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1734379287094921206,GWP_Rose1ml_Centella1ml_Hya1ml_Brush,[สินค้าแถม ห้ามกดสั่งซื้อ] แปรงแต่งหน้าเจ้านาง...,ค่าเริ่มต้น,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48057,582837066058728767,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1733392274824660982,Togo00_GLS01,แป้งพัฟเจ้านาง To go + รองพื้นซองเจ้านาง สูตร ...,"แป้งTo go 00, รองพื้น Glass Skin 01",1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48058,582837348412917082,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732261908704954358,8859460201531,Airy คุชชั่นเจ้านางแบบซอง(5ก.) บางเบา ปกปิด คุ...,02 GOLDEN HONEY,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48059,582837348412917082,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1734421965781895158,GWP_Rose1ml_Centella1ml_Hya1ml,[สินค้าแถม ห้ามกดสั่งซื้อ] เซรั่มเจ้านางขนาดทด...,ค่าเริ่มต้น,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
df_2024_Q1_cleaned = df_2024_Q1.iloc[1:].copy()
df_2024_Q234_cleaned = df_2024_Q234.iloc[1:].copy()

df2024 = pd.concat([df_2024_Q1_cleaned, df_2024_Q234_cleaned], ignore_index=True)
display(df2024.head())

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,579802935673522831,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133178870,8859460200466,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,03 ผิวเข้ม,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,579802882152892916,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,579802825830795537,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133113334,8859460200459,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,579802812881406721,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397643766,8859460200350,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,579802781183150805,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133244406,8859460200473,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,C21 ผิวขาวเหลือง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
df2024

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,579802935673522831,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133178870,8859460200466,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,03 ผิวเข้ม,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,579802882152892916,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,579802825830795537,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133113334,8859460200459,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,579802812881406721,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397643766,8859460200350,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,579802781183150805,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133244406,8859460200473,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,C21 ผิวขาวเหลือง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83178,578314965325351826,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437736950,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83179,578314684407253371,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437736950,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83180,578314672990751326,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,NaN,รองพื้นซอง ( 5g.) Chaonang Radiance Skin Found...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83181,578314661173430826,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437868022,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#03 คลาสสิค แทน,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83182,578314492702198502,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729443967437802486,NaN,รองพื้นหลอด( 15g.) Chaonang Radiance Skin Foun...,#02 ฮันนี่ เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# รวม Data

In [86]:
ttdf = pd.concat([df2024, df_2025, df2026], ignore_index=True)
display(ttdf.head())

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,579802935673522831,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133178870,8859460200466,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,03 ผิวเข้ม,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,579802882152892916,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,579802825830795537,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133113334,8859460200459,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,579802812881406721,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397643766,8859460200350,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,579802781183150805,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133244406,8859460200473,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,C21 ผิวขาวเหลือง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
ttdf

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,579802935673522831,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133178870,8859460200466,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,03 ผิวเข้ม,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,579802882152892916,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,579802825830795537,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133113334,8859460200459,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,579802812881406721,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397643766,8859460200350,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,579802781183150805,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133244406,8859460200473,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,C21 ผิวขาวเหลือง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305255,582837066058728767,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1734440271410464758,8859460201876,Care skin รองพื้นเจ้านางแคร์สกิน (5ก.) - Chaon...,00 ผิวขาว,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305256,582837066058728767,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1734379287094921206,GWP_Rose1ml_Centella1ml_Hya1ml_Brush,[สินค้าแถม ห้ามกดสั่งซื้อ] แปรงแต่งหน้าเจ้านาง...,ค่าเริ่มต้น,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305257,582837066058728767,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1733392274824660982,Togo00_GLS01,แป้งพัฟเจ้านาง To go + รองพื้นซองเจ้านาง สูตร ...,"แป้งTo go 00, รองพื้น Glass Skin 01",1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305258,582837348412917082,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732261908704954358,8859460201531,Airy คุชชั่นเจ้านางแบบซอง(5ก.) บางเบา ปกปิด คุ...,02 GOLDEN HONEY,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305259,582837348412917082,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1734421965781895158,GWP_Rose1ml_Centella1ml_Hya1ml,[สินค้าแถม ห้ามกดสั่งซื้อ] เซรั่มเจ้านางขนาดทด...,ค่าเริ่มต้น,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
ttdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305260 entries, 0 to 305259
Data columns (total 63 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Order ID                        305260 non-null  object
 1   Order Status                    305260 non-null  object
 2   Order Substatus                 305259 non-null  object
 3   Cancelation/Return Type         497 non-null     object
 4   Normal or Pre-order             291517 non-null  object
 5   SKU ID                          305260 non-null  object
 6   Seller SKU                      304442 non-null  object
 7   Product Name                    305260 non-null  object
 8   Variation                       305260 non-null  object
 9   Quantity                        305260 non-null  object
 10  Sku Quantity of return          305260 non-null  object
 11  SKU Unit Original Price         305260 non-null  object
 12  SKU Subtotal Before Discount    305260 non-null  object
 13  SKU Platform Discount           305260 non-null  object
 14  SKU Seller Discount             305260 non-null  object
 15  SKU Subtotal After Discount     305260 non-null  object
 16  Shipping Fee After Discount     305260 non-null  object
 17  Original Shipping Fee           305260 non-null  object
 18  Shipping Fee Seller Discount    305260 non-null  object
 19  Shipping Fee Platform Discount  305260 non-null  object
 20  Payment platform discount       4703 non-null    object
 21  Taxes                           305259 non-null  float64
 22  Order Amount                    305260 non-null  object
 23  Order Refund Amount             288 non-null     object
 24  Created Time                    305260 non-null  object
 25  Paid Time                       305260 non-null  object
 26  RTS Time                        305260 non-null  object
 27  Shipped Time                    305235 non-null  object
 28  Delivered Time                  305210 non-null  object
 29  Cancelled Time                  7 non-null       object
 30  Cancel By                       28 non-null      object
 31  Cancel Reason                   28 non-null      object
 32  Fulfillment Type                305259 non-null  object
 33  Warehouse Name                  305259 non-null  object
 34  Tracking ID                     305260 non-null  object
 35  Delivery Option                 305260 non-null  object
 36  Shipping Provider Name          305260 non-null  object
 37  Buyer Message                   370 non-null     object
 38  Buyer Username                  302608 non-null  object
 39  Recipient                       305259 non-null  object
 40  Phone #                         305259 non-null  object
 41  Zipcode                         305259 non-null  object
 42  Country                         305259 non-null  object
 43  Province                        305259 non-null  object
 44  District                        305259 non-null  object
 45  Districts                       0 non-null       float64
 46  Detail Address                  305259 non-null  object
 47  Additional address information  99750 non-null   object
 48  Payment Method                  291518 non-null  object
 49  Weight(kg)                      305259 non-null  float64
 50  Product Category                305260 non-null  object
 51  Package ID                      305260 non-null  object
 52  Seller Note                     0 non-null       float64
 53  Checked Status                  305259 non-null  object
 54  Checked Marked by               0 non-null       float64
 55  Request Tax Invoice             1 non-null       object
 56  Tax Info - Buyer Tax ID         1 non-null       object
 57  Tax Info - Type                 1 non-null       object
 58  Tax Info - Full Name of Buyer   1 non-null       object
 59  Tax Info - Email                1 non-null       object
 60  Tax Info - Phone Number         1 non-null       object
 61  Tax Info - Registered Address   1 non-null       object
 62  Tax Info - Address Type         1 non-null       object
dtypes: float64(5), object(58)
memory usage: 146.7+ MB

In [89]:
ttdf.isnull().sum()

Order ID                              0
Order Status                          0
Order Substatus                       1
Cancelation/Return Type          304763
Normal or Pre-order               13743
                                  ...
Tax Info - Full Name of Buyer    305259
Tax Info - Email                 305259
Tax Info - Phone Number          305259
Tax Info - Registered Address    305259
Tax Info - Address Type          305259
Length: 63, dtype: int64

In [90]:
print(f"Total number of orders (rows) in TTdf: {len(ttdf)}")

Total number of orders (rows) in TTdf: 305260

In [91]:
display(ttdf.head(5))

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Status,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type
0,579802935673522831,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133178870,8859460200466,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,03 ผิวเข้ม,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,579802882152892916,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#C21 เนเชอรัล เบจ,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,579802825830795537,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133113334,8859460200459,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,02 ผิวสองสี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,579802812881406721,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397643766,8859460200350,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#01 ไอโวรี,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,579802781183150805,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133244406,8859460200473,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,C21 ผิวขาวเหลือง,1,...,Unchecked,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
ttdf.to_csv('ttdf_exported.csv', index=False)
print('ttdf has been exported to ttdf_exported.csv')

ttdf has been exported to ttdf_exported.csv

# Calculate pay lag((timepayment − timecreate) ทุก order)

In [92]:
ttdf['Created Time'] = pd.to_datetime(ttdf['Created Time'], errors='coerce') #การแปลงข้อมูลให้เป็น "วันที่"
ttdf['Paid Time'] = pd.to_datetime(ttdf['Paid Time'], errors='coerce') #ทำกับคอลัมน์ Paid Time
ttdf['Pay Lag'] = ttdf['Paid Time'] - ttdf['Created Time'] #คำนวณส่วนต่างเวลา (Pay Lag) เวลาจ่ายเงิน ลบด้วย เวลาที่สร้าง
display(ttdf[['Created Time', 'Paid Time', 'Pay Lag']]) #ดูเฉพาะ 3 คอลัมน์ที่เราสนใจ (Created Time, Paid Time, Pay Lag)

/tmp/ipykernel_2941/1602825636.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ttdf['Created Time'] = pd.to_datetime(ttdf['Created Time'], errors='coerce') #การแปลงข้อมูลให้เป็น "วันที่"
/tmp/ipykernel_2941/1602825636.py:2: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ttdf['Paid Time'] = pd.to_datetime(ttdf['Paid Time'], errors='coerce') #ทำกับคอลัมน์ Paid Time

              Created Time           Paid Time         Pay Lag
0      2024-12-25 23:35:50 2024-12-28 16:08:03 2 days 16:32:13
1      2024-12-25 23:14:19 2024-12-27 17:45:18 1 days 18:30:59
2      2024-12-25 22:56:32 2024-12-25 22:56:57 0 days 00:00:25
3      2024-12-25 22:52:36 2024-12-27 16:05:40 1 days 17:13:04
4      2024-12-25 22:43:21 2024-12-25 22:43:41 0 days 00:00:20
...                    ...                 ...             ...
305255 2026-02-28 23:51:49 2026-02-28 23:51:58 0 days 00:00:09
305256 2026-02-28 23:51:49 2026-02-28 23:51:58 0 days 00:00:09
305257 2026-02-28 23:51:49 2026-02-28 23:51:58 0 days 00:00:09
305258 2026-02-28 23:52:48 2026-03-03 14:38:13 2 days 14:45:25
305259 2026-02-28 23:52:48 2026-03-03 14:38:13 2 days 14:45:25

[305260 rows x 3 columns]

In [94]:
ttdf

,Order ID,Order Status,Order Substatus,Cancelation/Return Type,Normal or Pre-order,SKU ID,Seller SKU,Product Name,Variation,Quantity,...,Checked Marked by,Request Tax Invoice,Tax Info - Buyer Tax ID,Tax Info - Type,Tax Info - Full Name of Buyer,Tax Info - Email,Tax Info - Phone Number,Tax Info - Registered Address,Tax Info - Address Type,Pay Lag
0,579802935673522831,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133178870,8859460200466,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,03 ผิวเข้ม,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 days 16:32:13
1,579802882152892916,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397840374,8859460200398,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#C21 เนเชอรัล เบจ,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 days 18:30:59
2,579802825830795537,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133113334,8859460200459,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,02 ผิวสองสี,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days 00:00:25
3,579802812881406721,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729440166397643766,8859460200350,รองพื้นเจ้านาง แบบซอง (5ก.) - Chaonang Radianc...,#01 ไอโวรี,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 days 17:13:04
4,579802781183150805,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1729986743133244406,8859460200473,รองพื้นเจ้านาง (15ก.) - Chaonang Radiance Skin...,C21 ผิวขาวเหลือง,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days 00:00:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305255,582837066058728767,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1734440271410464758,8859460201876,Care skin รองพื้นเจ้านางแคร์สกิน (5ก.) - Chaon...,00 ผิวขาว,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days 00:00:09
305256,582837066058728767,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1734379287094921206,GWP_Rose1ml_Centella1ml_Hya1ml_Brush,[สินค้าแถม ห้ามกดสั่งซื้อ] แปรงแต่งหน้าเจ้านาง...,ค่าเริ่มต้น,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days 00:00:09
305257,582837066058728767,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1733392274824660982,Togo00_GLS01,แป้งพัฟเจ้านาง To go + รองพื้นซองเจ้านาง สูตร ...,"แป้งTo go 00, รองพื้น Glass Skin 01",1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 days 00:00:09
305258,582837348412917082,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1732261908704954358,8859460201531,Airy คุชชั่นเจ้านางแบบซอง(5ก.) บางเบา ปกปิด คุ...,02 GOLDEN HONEY,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 days 14:45:25
305259,582837348412917082,เสร็จสมบูรณ์,เสร็จสมบูรณ์,NaN,Normal,1734421965781895158,GWP_Rose1ml_Centella1ml_Hya1ml,[สินค้าแถม ห้ามกดสั่งซื้อ] เซรั่มเจ้านางขนาดทด...,ค่าเริ่มต้น,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 days 14:45:25

In [95]:
ttdf.to_excel('ttdf_exported.xlsx', index=False)
print('ttdf has been exported to ttdf_exported.xlsx')

ttdf has been exported to ttdf_exported.xlsx